{% set name = "graphbrain" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38ce60c8645e4b32a351e3f5bf92411935edca964b0cd8540847ce3bf960cf2d

build:
  number: 0
  skip: true  # [py>37]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - graphbrain = graphbrain.__main__:cli

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - asciitree
    - ipython
    - numpy
    - plyvel
    - progressbar2
    - python
    - python-igraph
    - spacy
    - termcolor
    - unidecode

test:
  imports:
    - graphbrain
    - graphbrain.agents

about:
  home: https://pypi.org/project/graphbrain/
  summary: Knowledge System + Natural Language Understanding.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
