{% set name = "graphbrain" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cef4e32ce9bb93504029e4e1ea8a31affa36d54393521d8615496f67f14b5be6
  patches:
    - utf8_encoding.patch

build:
  number: 0
  skip: true  # [py>37]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - graphbrain = graphbrain.__main__:cli

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - asciitree
    - ipython
    - numpy
    - plyvel
    - progressbar2
    - python
    - python-igraph
    - spacy
    - termcolor
    - unidecode

test:
  imports:
    - graphbrain

about:
  home: https://pypi.org/project/graphbrain/
  summary: Knowledge System and Natural Language Understanding.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
    - mxr-conda
